[workspace]
members = [
    "rusteron-code-gen",
    "rusteron-rb",
    "rusteron-media-driver",
    "rusteron-client",
    "rusteron-archive",
]
exclude = ["rusteron-docker-samples/rusteron-dummy-example"]
resolver = "2"

[workspace.dependencies]
rusteron-code-gen = { path = "rusteron-code-gen", version = "0.1.94" }
ctrlc = "3.4"
bindgen = "0.71"
cmake = "0.1"
dunce = "1.0"
pkg-config = "0.3"
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
quote = "1.0"
itertools = "0.14"
num-format = "0.4"
hdrhistogram = "7.5"
criterion = "0.5"
serial_test = "3.2"
regex = "1.11"
log = "0.4"
glob = "0.3.2"
walkdir = "2.5.0"

[release]
bump = "auto"
update_dependencies = true
publish = true
workspace = true
auto_publish = true
push = true
tag = true
dependency_version = "update"
consolidate_commits = true
allow_dirty = true
no_confirm = true
update_crates_index = true
verify = false

[profile.release]
#opt-level = 3
debug = true
debug-assertions = false
overflow-checks = false
lto = "thin"
