[package]
name = "rusteron-client"
version = "0.1.27"
edition = "2021"
authors = ["Mo Imran <mimran1980@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/mimran1980/rusteron"
homepage = "https://github.com/mimran1980/rusteron"
keywords = ["aeron", "low-latency", "client", "bindings", "networking"]
categories = ["network-programming"]
documentation = "https://mimran1980.github.io/rusteron/rusteron_client/index.html"
description = "Provides core client functionalities for interacting with the Aeron protocol, such as establishing connections, subscribing, and publishing. It uses the Aeron C bindings from aeron-client module."
readme = "README.md"

[dependencies]
ctrlc = { workspace = true }
num-format = {  workspace = true }
hdrhistogram = { workspace = true}
zerocopy = { workspace = true }

[build-dependencies]
bindgen = {  workspace = true }
cmake = {  workspace = true }
dunce = {  workspace = true }
pkg-config = {  workspace = true }
syn = {  workspace = true }
proc-macro2 = {  workspace = true }
quote = {  workspace = true }
itertools = {  workspace = true }
rusteron-code-gen = {path = "../rusteron-code-gen", version = "0"}

[dev-dependencies]
rusteron-media-driver = {path = "../rusteron-media-driver"}
serial_test = "3.1"

[features]
static = ["rusteron-media-driver/static"]
