[package]
name = "rusteron-client"
version = "0.1.132"
edition = "2021"
authors = ["Mo Imran <mimran1980@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/mimran1980/rusteron"
homepage = "https://github.com/mimran1980/rusteron"
keywords = ["aeron", "low-latency", "aeron-client", "aeron-c-bindings", "networking"]
categories = ["network-programming"]
documentation = "https://mimran1980.github.io/rusteron/rusteron_client/index.html"
description = "Provides core client functionalities for interacting with the Aeron protocol, such as establishing connections, subscribing, and publishing. It uses the Aeron C bindings from aeron-client module."
readme = "README.md"

exclude = [
    "aeron/.gradle/**",
    "aeron/buildSrc/.gradle/**",
    "aeron/build/**",
    "aeron/aeron-agent/build/**",
    "aeron/aeron-all/build/**",
    "aeron/aeron-annotations/build/**",
    "aeron/aeron-archive/build/**",
    "aeron/aeron-client/build/**",
    "aeron/aeron-cluster/build/**",
    "aeron/aeron-driver/build/**",
    "aeron/aeron-samples/build/**",
    "aeron/aeron-system-tests/build/**",
    "aeron/aeron-test-support/build/**",
    "aeron/buildSrc/build/**",
]


[dependencies]
ctrlc = { workspace = true }
num-format = {  workspace = true }
hdrhistogram = { workspace = true}
log = { workspace = true}
regex = { workspace = true}


[build-dependencies]
bindgen = {  workspace = true }
cmake = {  workspace = true }
dunce = {  workspace = true }
pkg-config = {  workspace = true }
proc-macro2 = {  workspace = true }
rusteron-code-gen = { workspace = true }
log = { workspace = true}
regex = { workspace = true}
walkdir = { workspace = true}
reqwest = {workspace = true}
flate2 = {workspace = true}
tar    = {workspace = true}



[dev-dependencies]
rusteron-media-driver = {path = "../rusteron-media-driver"}
serial_test = { workspace = true }
criterion = {workspace = true}
env_logger = "0.11"

[features]
# using static as different modules have different versions of aeron which don't seem to play nicely
default = []
static = ["rusteron-media-driver/static"]
# logs the backtrace on each AeronCError
backtrace = []
extra-logging = []
precompile = []

[[bench]]
name = "ping_pong"
harness = false

[[bench]]
name = "ping_pong_ipc"
harness = false

[package.metadata.docs.rs]
features = ["static", "precompile"]
default-target = "x86_64-apple-darwin"
