[package]
name = "rusteron-code-gen"
version = "0.1.0"
authors = ["Mohammed Imran <mimran1980@gmail.com>"]
repository = "https://github.com/mimran1980/rusteron"
documentation = "https://docs.rs/rusteron"
description = "Code generator for aeron c bindings"
license = "Apache-2.0"
edition = "2021"
#readme = "README.md"

[dependencies]
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0.86"
quote = "1.0"
itertools = "0.13"
log = "0.4.22"

[dev-dependencies]
trybuild = "1.0"

[features]
static = []
