[package]
name = "rusteron-media-driver"
version = "0.1.16"
edition = "2021"
authors = ["Mo Imran <mimran1980@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/mimran1980/rusteron"
homepage = "https://github.com/mimran1980/rusteron"
keywords = ["aeron", "low-latency", "media-driver", "bindings", "networking"]
categories = ["network-programming"]
documentation = "https://mimran1980.github.io/rusteron/rusteron_media_driver/index.html"
description = "Implements the Aeron Media Driver, a core component for managing messaging between producers and consumers. It uses the Aeron C bindings from aeron-driver module."
readme = "README.md"

[dependencies]
ctrlc = { workspace = true }

[build-dependencies]
bindgen = {  workspace = true }
cmake = {  workspace = true }
dunce = {  workspace = true }
pkg-config = {  workspace = true }
syn = {  workspace = true }
proc-macro2 = {  workspace = true }
quote = {  workspace = true }
itertools = {  workspace = true }
rusteron-code-gen = {path = "../rusteron-code-gen", version = "0"}

[features]
static = []

[[bin]]
name = "media_driver"
path = "src/bin/media_driver.rs"
